server:
  port: 8080

spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
#    - url: http://www.playback.ru
#      name: PlayBack.ru
#    - url: https://volochek.life
#      name: Вышний Волочёк
    - url: https://radiomv.ru
      name: Милицейская волна
    - url: https://ipfran.ru
      name: Институт прикладной физики Российской академии наук
    - url: https://dimonvideo.ru
      name: DIMONVIDEO
#    - url: https://nikoartgallery.com
#      name: Niko ART GALLERY
#    - url: https://et-cetera.ru/mobile
#      name: Театр «Et Cetera»
#    - url: https://www.lutherancathedral.ru
#      name: Кафедральный собор святых Петра и Павла
#    - url: https://dombulgakova.ru
#      name: Булгаковскiй домъ
#    - url: https://www.svetlovka.ru
#      name: Светловка
#    - url: https://lenta.ru
#      name: Лента.ру